### ISSUE TITLE
Stays on top

### ISSUE THREAD

**Issue by TheDragonSlays** [giabao4498/Hydra-Virus#11]
Can you make it so the windows will stay on top even if you select another window?
This might work: https://stackoverflow.com/questions/683330/how-to-make-a-window-always-stay-on-top-in-net

**Comment by giabao4498** [comment]
Thank you so much for your suggestion! I updated the virus and now it always stays on top. Even `Windows + D` can't minimize it.

**Comment by TheDragonSlays** [comment]
That should make it WAY more annoying
