### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by deeznutzboi777** [giabao4498/Hydra-Virus#13]
for some reason my windows defender says that there is a trojan on it.
is this normal?

**Comment by giabao4498** [comment]
Hmm maybe there's something wrong with Windows Defender. If you look at the source code, you'll see that there's no harm to run it.

**Comment by GEOEGII555** [comment]
> Hmm maybe there's something wrong with Windows Defender. If you look at the source code, you'll see that there's no harm to run it.

It's harmless, but it's still a virus, so Windows Defender won't let you run it.

**Comment by giabao4498** [comment]
@GEOEGII555 Yup, Windows Defender blocks it now, but not in the past. Now you need to exclude it from Windows Defender in order to run it.
