### ISSUE TITLE
Does this virus corrupt files and or can it be uninstalled

### ISSUE THREAD

**Issue by ToastyGuRu** [giabao4498/Hydra-Virus#5]
Hey, I want to prank my friend by adding this to a flash drive and add it to his old pc. I read that this can be stopped by taskmanager that is great! Will this run on startup? Also, can I uninstall this once im done with the prank?

**Comment by giabao4498** [comment]
Hi! This virus can't run on startup. When you're done, just simply delete it like a normal file. Also, it's harmless, no need to worry about corrupting files. Have fun :)
